<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>SEMANA 5</title>
</head>
<body>
    
<div>
  <h2>Carrito de Donaciones</h2>
  
<a href="agregar.php">
  <button>Agregar Donacion</button>
</a>

<a href="carrito.php">
  <button>Ver Carrito</button>
</a>
</div>

</body>
</html>